### ISSUE TITLE
[FYI] Now available from ArchLinux User Repository (AUR)

### ISSUE THREAD

**Issue by kseistrup** [igrek51/wat#16]
[ This issue is purely information: No action is necessary on your part, and the issue can be closed at your discretion. ]

WAT is now available from AUR as `python-wat-git`:

* https://aur.archlinux.org/packages/python-wat-git

It can be installed using an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers) — e.g. `yay`:

```sh
» yay -S python-wat-git
```

:pray:

**Comment by igrek51** [comment]
That's really cool. Thank you
