### ISSUE TITLE
`__all__` is not respected

### ISSUE THREAD

**Issue by zed** [igrek51/wat#27]
Given `module_with_all.py`:

```python
__all__ = ["the_only_public_name"]

def the_only_public_name():
    """It should be the only public name in this module."""


def this_is_not_public():
    ...

def _prefix_with_underscore_is_tiresome_with_few_public_names():
    ...
```
I would expect that `the_only_public_name`  is listed as public attribute and just it, nothing else. Instead `this_is_not_public` is listed as public too:

```
>>> import module_with_all as M
>>> import wat
>>> wat / M
────────────────────────────────────────────────────────────────────────────────value: <module 'module_with_all' from '/respect-all/module_with_all.py'>
type: module

Public attributes:
  def the_only_public_name() # It should be the only public name in this module. 
  def this_is_not_public()

Private attributes:
  def _prefix_with_underscore_is_tiresome_with_few_public_names()
────────────────────────────────────────────────────────────────────────────────
```

**Comment by zed** [comment]
Often `__all__` is used to express Python package author's *intent* on what names are public (exported). Otherwise, you have to prefix with `_` all the names that are not public in the module--it is ugly, especially  when there are just a few public names while there are a lot of internal/implementation-only details. 

Python allows you to access  "_private" attributes as well--but they are listed separately above (as they should). 

You can even rebind a builtin or get  `self.__private` attribute outside (`_<classname>__private`) --it doesn't make it a good idea.

Given the purpose of the tool, listing such names as `TYPE_CHECKING`, `os`, `sys`, etc is just noise (at least for the public section).

If there is non-empty `__all__`, it can help filter relevant/from irrelevant names.

**Comment by igrek51** [comment]
I see your point. It may look odd indeed, but that's how Python works. And *wat* is just a tool helping to learn and understand this kind of Python's quirks. Python has lot of them, hence the name "wat" 😉 
I hope it did its job and helped you to learn something new
