### ISSUE TITLE
show non-abbreviated values but without functions docs?

### ISSUE THREAD

**Issue by tkossak** [igrek51/wat#35]
Hi, is it possible to show non-abbreviated values without functions docs (docs take too much space)? I tried:
- `wat.short` abbreviates values (I don't see full dicts/lists)
- `wat.long` takes too much space beacuse of functions docs
- `wat.long.nodocs` seems the same as `wat.long` - prints functions docs.

wat version 0.4.2

**Comment by igrek51** [comment]
Indeed, there's something wrong. `.nodocs` hides the docs of an inspected object, but not the docs of its attributes.
Thanks for pointing this out. I'll fix that.

**Comment by igrek51** [comment]
@tkossak It's now released in version 0.4.3

**Comment by tkossak** [comment]
Thank you very much, works perfectly :)

**Comment by tkossak** [comment]
Btw. not sure if it will work for you (maybe you need to support some strange pythons, without `pkg_resources` package) but for my cases I use:
`__version__ = pkg_resources.get_distribution('<MY_MODULE_NAME>').version`
It returns version of installed package, so I don't have to write new version twice (I only keep it in `pyproject.toml` and not directly in [version.py](https://github.com/igrek51/wat/blob/master/wat/version.py)).

**Comment by igrek51** [comment]
Ah, but I see it's part of the setuptools package which stands in conflict with my approach to have zero external dependencies. Also it seems to be deprecated. Possibly, I'd like it the other way around - to keep the version in one place in version.py and to refer to it somehow in pyproject.toml

**Comment by tkossak** [comment]
There's also [importlib](https://docs.python.org/3/library/importlib.html) in python - seems better solution than pkg_resources :)

```
import importlib.metadata
__version__ = importlib.metadata.version('MY_MODULE_NAME')
```

**Comment by igrek51** [comment]
Thanks, I figured this the other way around by doing this:
https://github.com/igrek51/wat/blob/ccd9dc26bbfca92d7e09edaceae12c8fb19b22e5/pyproject.toml#L26

**Comment by tkossak** [comment]
Didn't know that, thank you! :)
