### ISSUE TITLE
Wat with a QT GUI   -- not a bug, but seems best way to reach you.

### ISSUE THREAD

**Issue by russ-hensel** [igrek51/wat#37]
Wat with a QT GUI   -- not a bug, but seems best way to reach you.

I really like your wat inspection tool, but I am not a command line guy, I like a GUI, and I mostly program in a GUI.  So I did an adaptation of wat that presents the material in a GUI format and also
adds a few other bits and pieces.

This was done as a sub project to a much larger and largely unfinished/unpolished project I call qt_by_example.

The whole hot mess is at https://github.com/russ-hensel/qt_by_example/tree/main .  See the non-install comments in the readme.md.

I would be interested in your reaction, but if you are not a QT user I will understand.  Other uses of wat may also find this of interest.

Russ

**Comment by igrek51** [comment]
@russ-hensel  Thanks for letting me know. This looks nice. I'm glad my project was useful to you.
I tried running yours, and I think you should clarify what are requirements and how to set it up and run it. For instance, the good practice is to keep `pyproject.toml` or `requirements.txt` in repository which contains prerequisites, in your case it would be:
```
PyQt5
wat-inspector
```

 I wish good luck to your project.

**Comment by russ-hensel** [comment]
You are right about the packaging, I do not package my projects because of the low ( 0 ) interest they seem to get
from others.  I will help anyone who want it with information on the install.  If that is very many people I will learn packaging.
