### ISSUE TITLE
Make it globally installable via homebrew?

### ISSUE THREAD

**Issue by Coinhexa** [igrek51/wat#5]
Add this library to homebrew so that It doesn't have to be installed for just one particular project and is available globally?

**Comment by igrek51** [comment]
Doesn't it make it available globally if you just do this?:
```shell
pip install wat-inspector
```
and if you want it available in virtual environments, you can do:
```shell
python -m venv --system-site-packages venv
```

Let me know if that makes what you wanted. I'm not familiar with homebrew, so maybe I might be wrong somewhere.

Nevertheless, if it can be done with standard Python tools, I'd like to avoid keeping this package (and maintaining it) in another place.
